export type SavedSong = { id: string; title: string; artist: string; sourceUrl: string; kind: "Chords" | "Tab"; custom?: boolean };

type RawSong = [title: string, artist: string, sourceUrl: string, kind?: "Tab"];

const RAW: RawSong[] = [
  ["A Horse With No Name","America","https://tabs.ultimate-guitar.com/tab/america/a-horse-with-no-name-chords-59609"],
  ["In The Aeroplane Over The Sea","Neutral Milk Hotel","https://tabs.ultimate-guitar.com/tab/neutral-milk-hotel/in-the-aeroplane-over-the-sea-chords-35827"],
  ["Wagon Wheel","Darius Rucker","https://tabs.ultimate-guitar.com/tab/darius-rucker/wagon-wheel-chords-1215756"],
  ["Clay Pigeons (ver 2)","John Prine","https://tabs.ultimate-guitar.com/tab/john-prine/clay-pigeons-chords-1197098"],
  ["Good Riddance Time Of Your Life (ver 3)","Green Day","https://tabs.ultimate-guitar.com/tab/green-day/good-riddance-time-of-your-life-chords-31443"],
  ["My Church (ver 3)","Maren Morris","https://tabs.ultimate-guitar.com/tab/maren-morris/my-church-chords-1838945"],
  ["Let Your Heart Hold Fast (ver 3)","Fort Atlantic","https://tabs.ultimate-guitar.com/tab/fort-atlantic/let-your-heart-hold-fast-chords-1202604"],
  ["Valerie (ver 3)","Mark Ronson","https://tabs.ultimate-guitar.com/tab/mark-ronson/valerie-chords-738108"],
  ["Iris (ver 7)","Goo Goo Dolls","https://tabs.ultimate-guitar.com/tab/goo-goo-dolls/iris-chords-822601"],
  ["Truly Madly Deeply (ver 2)","Yoke Lore","https://tabs.ultimate-guitar.com/tab/yoke-lore/truly-madly-deeply-chords-2888678"],
  ["Yihyeh Tov","David Broza","https://tabs.ultimate-guitar.com/tab/david-broza/yihyeh-tov-chords-2374385"],
  ["Beige","Yoke Lore","https://tabs.ultimate-guitar.com/tab/yoke-lore/beige-chords-2448463"],
  ["Alaska","Maggie Rogers","https://tabs.ultimate-guitar.com/tab/maggie-rogers/alaska-chords-1854410"],
  ["Casual (ver 2)","Chappell Roan","https://tabs.ultimate-guitar.com/tab/chappell-roan/casual-chords-4404614"],
  ["Better Than","Lake Street Dive","https://tabs.ultimate-guitar.com/tab/lake-street-dive/better-than-chords-1494228"],
  ["Death Of A Bachelor","Panic! At the Disco","https://tabs.ultimate-guitar.com/tab/panic-at-the-disco/death-of-a-bachelor-chords-1764430"],
  ["Riptide (ver 2)","Vance Joy","https://tabs.ultimate-guitar.com/tab/vance-joy/riptide-chords-1237247"],
  ["Lashuv Habaita","Ishay Ribo","https://tabs.ultimate-guitar.com/tab/ishay-ribo/lashuv-habaita-chords-3056677"],
  ["Lmaancha","Eitan Katz","https://tabs.ultimate-guitar.com/tab/eitan-katz/lmaancha-chords-1494862"],
  ["Vehi Sheamda","Yaakov Shwekey","https://tabs.ultimate-guitar.com/tab/yaakov-shwekey/vehi-sheamda-chords-2027135"],
  ["Oof Gozal - Fly Fledgling","Arik Einstein","https://tabs.ultimate-guitar.com/tab/arik-einstein/oof-gozal-fly-fledgling-chords-2380099"],
  ["Ani Veata","Arik Einstein","https://tabs.ultimate-guitar.com/tab/arik-einstein/ani-veata-chords-3242549"],
  ["Vezakeini","Baruch Levine","https://tabs.ultimate-guitar.com/tab/baruch-levine/vezakeini-chords-2731482"],
  ["Bilvavi","Ohr Chodosh","https://tabs.ultimate-guitar.com/tab/ohr-chodosh/bilvavi-chords-2989610"],
  ["House Of The Rising Sun","The Animals","https://tabs.ultimate-guitar.com/tab/the-animals/house-of-the-rising-sun-chords-18688"],
  ["Long Monday (ver 2)","John Prine","https://tabs.ultimate-guitar.com/tab/john-prine/long-monday-chords-937695"],
  ["I Am California","John Craigie","https://tabs.ultimate-guitar.com/tab/john-craigie/i-am-california-chords-1963467"],
  ["Landslide (ver 2)","Fleetwood Mac","https://tabs.ultimate-guitar.com/tab/fleetwood-mac/landslide-chords-1048613"],
  ["The Night We Met","Lord Huron","https://tabs.ultimate-guitar.com/tab/lord-huron/the-night-we-met-chords-1709964"],
  ["Angel From Montgomery (ver 2)","John Prine","https://tabs.ultimate-guitar.com/tab/john-prine/angel-from-montgomery-chords-604233"],
  ["Tequila","Dan + Shay","https://tabs.ultimate-guitar.com/tab/dan-shay/tequila-chords-2279411"],
  ["Seven English Girls","Ron Pope","https://tabs.ultimate-guitar.com/tab/ron-pope/seven-english-girls-chords-781948"],
  ["Make You Feel My Love","Adele","https://tabs.ultimate-guitar.com/tab/adele/make-you-feel-my-love-chords-752102"],
  ["Sober","Joy Oladokun","https://tabs.ultimate-guitar.com/tab/joy-oladokun/sober-chords-2881595"],
  ["Kiss Me","Sixpence None The Richer","https://tabs.ultimate-guitar.com/tab/sixpence-none-the-richer/kiss-me-chords-2704"],
  ["Lean On Me (ver 2)","Bill Withers","https://tabs.ultimate-guitar.com/tab/bill-withers/lean-on-me-chords-195090"],
  ["Hallelujah (ver 2)","Jeff Buckley","https://tabs.ultimate-guitar.com/tab/jeff-buckley/hallelujah-chords-198052"],
  ["Marry You (ver 3)","Bruno Mars","https://tabs.ultimate-guitar.com/tab/bruno-mars/marry-you-chords-1009718"],
  ["Wonderwall (ver 3)","Oasis","https://tabs.ultimate-guitar.com/tab/oasis/wonderwall-chords-39144"],
  ["All Of Me","John Legend","https://tabs.ultimate-guitar.com/tab/john-legend/all-of-me-chords-1248578"],
  ["Hotel California","Eagles","https://tabs.ultimate-guitar.com/tab/eagles/hotel-california-chords-46190"],
  ["Take Me Home Country Roads (ver 5)","John Denver","https://tabs.ultimate-guitar.com/tab/john-denver/take-me-home-country-roads-chords-1101747"],
  ["Yoshimi Battles The Pink Robots Part 1","The Flaming Lips","https://tabs.ultimate-guitar.com/tab/the-flaming-lips/yoshimi-battles-the-pink-robots-part-1-chords-50106"],
  ["Feathered Indians","Tyler Childers","https://tabs.ultimate-guitar.com/tab/tyler-childers/feathered-indians-chords-1781024"],
  ["Lady May","Tyler Childers","https://tabs.ultimate-guitar.com/tab/tyler-childers/lady-may-chords-2099981"],
  ["All Yourn","Tyler Childers","https://tabs.ultimate-guitar.com/tab/tyler-childers/all-yourn-chords-2741586"],
  ["Nose On The Grindstone","Tyler Childers","https://tabs.ultimate-guitar.com/tab/tyler-childers/nose-on-the-grindstone-chords-1813943"],
  ["Follow You To Virgie","Tyler Childers","https://tabs.ultimate-guitar.com/tab/tyler-childers/follow-you-to-virgie-chords-2215039"],
  ["Charleston Girl","Tyler Childers","https://tabs.ultimate-guitar.com/tab/tyler-childers/charleston-girl-chords-2042817"],
  ["All Your Favorite Bands","Dawes","https://tabs.ultimate-guitar.com/tab/dawes/all-your-favorite-bands-chords-1742163"],
  ["A Little Bit Of Everything","Dawes","https://tabs.ultimate-guitar.com/tab/dawes/a-little-bit-of-everything-chords-1040824"],
  ["Ooh La La (ver 3)","Faces","https://tabs.ultimate-guitar.com/tab/faces/ooh-la-la-chords-1410484"],
  ["The Crane Wife 3","The Decemberists","https://tabs.ultimate-guitar.com/tab/the-decemberists/the-crane-wife-3-chords-410321"],
  ["Down By The Water (ver 2)","The Decemberists","https://tabs.ultimate-guitar.com/tab/the-decemberists/down-by-the-water-chords-1000981"],
  ["Mariners Revenge Song","The Decemberists","https://tabs.ultimate-guitar.com/tab/the-decemberists/mariners-revenge-song-chords-271523"],
  ["Sons And Daughters","The Decemberists","https://tabs.ultimate-guitar.com/tab/the-decemberists/sons-and-daughters-chords-1203256"],
  ["The Boxer","Simon & Garfunkel","https://tabs.ultimate-guitar.com/tab/simon-garfunkel/the-boxer-chords-83970"],
  ["April Come She Will","Simon & Garfunkel","https://tabs.ultimate-guitar.com/tab/simon-garfunkel/april-come-she-will-chords-641222"],
  ["The Curse (ver 2)","Josh Ritter","https://tabs.ultimate-guitar.com/tab/josh-ritter/the-curse-chords-999780"],
  ["Hatikva Israeli National Anthem","Misc Traditional","https://tabs.ultimate-guitar.com/tab/misc-traditional/hatikva-israeli-national-anthem-chords-1045546"],
  ["Romeo And Juliet (ver 3)","Dire Straits","https://tabs.ultimate-guitar.com/tab/dire-straits/romeo-and-juliet-chords-1166247"],
  ["Wild West End","Dire Straits","https://tabs.ultimate-guitar.com/tab/dire-straits/wild-west-end-chords-15424"],
  ["Let Her Go","Passenger","https://tabs.ultimate-guitar.com/tab/passenger/let-her-go-chords-1137467"],
  ["Boulevard Of Broken Dreams (ver 3)","Green Day","https://tabs.ultimate-guitar.com/tab/green-day/boulevard-of-broken-dreams-chords-146744"],
  ["Slip Slidin Away (ver 4)","Paul Simon","https://tabs.ultimate-guitar.com/tab/paul-simon/slip-slidin-away-chords-1052992"],
  ["Im Yours (ver 11)","Jason Mraz","https://tabs.ultimate-guitar.com/tab/jason-mraz/im-yours-chords-373896"],
  ["Over The Rainbow","Israel Kamakawiwoʻole","https://tabs.ultimate-guitar.com/tab/868611"],
  ["By And By","Caamp","https://tabs.ultimate-guitar.com/tab/caamp/by-and-by-chords-2773876"],
  ["Years","Sierra Ferrell","https://tabs.ultimate-guitar.com/tab/sierra-ferrell/years-chords-4299722"],
  ["Rhiannon (ver 2)","Fleetwood Mac","https://tabs.ultimate-guitar.com/tab/fleetwood-mac/rhiannon-chords-1051646"],
  ["Dont Carry It All (ver 2)","The Decemberists","https://tabs.ultimate-guitar.com/tab/the-decemberists/dont-carry-it-all-chords-1017988"],
  ["Sons And Daughters","The Decemberists","https://tabs.ultimate-guitar.com/tab/the-decemberists/sons-and-daughters-tabs-407334","Tab"],
  ["Stubborn Love","The Lumineers","https://tabs.ultimate-guitar.com/tab/the-lumineers/stubborn-love-chords-1144923"],
  ["I Wish I Was","The Avett Brothers","https://tabs.ultimate-guitar.com/tab/the-avett-brothers/i-wish-i-was-chords-1856712"],
  ["Vagabond","Caamp","https://tabs.ultimate-guitar.com/tab/caamp/vagabond-chords-2403189"],
  ["Chicago","flipturn","https://tabs.ultimate-guitar.com/tab/flipturn/chicago-chords-3135968"],
  ["Twist And Shout (ver 2)","The Beatles","https://tabs.ultimate-guitar.com/tab/the-beatles/twist-and-shout-chords-489173"],
  ["Brown Eyed Girl (ver 4)","Van Morrison","https://tabs.ultimate-guitar.com/tab/van-morrison/brown-eyed-girl-chords-819644"],
  ["Heavy","Birdtalker","https://tabs.ultimate-guitar.com/tab/birdtalker/heavy-chords-1867136"],
  ["The Otter","Caamp","https://tabs.ultimate-guitar.com/tab/caamp/the-otter-chords-4246519"],
  ["American Beauty","Drew Holcomb and The Neighbors","https://tabs.ultimate-guitar.com/tab/drew-holcomb-and-the-neighbors/american-beauty-chords-1726390"],
  ["Piazza New York Catcher","Belle and Sebastian","https://tabs.ultimate-guitar.com/tab/belle-and-sebastian/piazza-new-york-catcher-chords-476509"],
  ["No Hard Feelings","The Avett Brothers","https://tabs.ultimate-guitar.com/tab/the-avett-brothers/no-hard-feelings-chords-1856008"],
  ["All I Want","Kodaline","https://tabs.ultimate-guitar.com/tab/kodaline/all-i-want-chords-1180259"],
  ["Soulfight","The Revivalists","https://tabs.ultimate-guitar.com/tab/the-revivalists/soulfight-chords-1492171"],
  ["Wildfire","Watchhouse (Mandolin Orange)","https://tabs.ultimate-guitar.com/tab/watchhouse-mandolin-orange/wildfire-chords-1884078"],
  ["Dont Let Me Down","Joy Crookes","https://tabs.ultimate-guitar.com/tab/joy-crookes/dont-let-me-down-chords-2613978"],
  ["Call You Home","Mangas Colorado","https://tabs.ultimate-guitar.com/tab/mangas-colorado/call-you-home-chords-1812808"],
  ["Fade Into You (ver 2)","Mazzy Star","https://tabs.ultimate-guitar.com/tab/mazzy-star/fade-into-you-chords-910099"],
  ["Blue Ridge Mountains (ver 4)","Fleet Foxes","https://tabs.ultimate-guitar.com/tab/fleet-foxes/blue-ridge-mountains-chords-1042364"],
  ["Rivers And Roads","The Head and the Heart","https://tabs.ultimate-guitar.com/tab/the-head-and-the-heart/rivers-and-roads-chords-1026669"],
  ["Im With You","Vance Joy","https://tabs.ultimate-guitar.com/tab/vance-joy/im-with-you-tabs-2325077","Tab"],
  ["Willys Song (ver 2)","Rayland Baxter","https://tabs.ultimate-guitar.com/tab/rayland-baxter/willys-song-chords-3112253"],
  ["A Thousand Years","Christina Perri","https://tabs.ultimate-guitar.com/tab/christina-perri/a-thousand-years-chords-1101795"],
];

export const SAVED_SONGS: SavedSong[] = RAW.map(([title, artist, sourceUrl, kind]) => ({
  id: sourceUrl.match(/(\d+)$/)?.[1] ?? sourceUrl,
  title,
  artist,
  sourceUrl,
  kind: kind ?? "Chords",
}));
